import Head from 'next/head'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contacts from '../components/Contacts'
import Blogs from '../components/Blogs'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import {sortByDate} from '../utils'

export default function Home({posts}) {
  //console.log(posts)
  return (
    <div>
      <Head>
        <title>Thajun Najaah | Senior Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Blogs posts={posts}/>
      <Contacts/>
    </div>
  )
}

export async function getStaticProps(){
  //Get files from posts directory
  const files = fs.readdirSync(path.join('posts'))

  //console.log(files)

  //Get Slug and frontmatter from posts
  const posts = files.map(filename => {
    //Create slug
    const slug = filename.replace('.md', '')

    //Create frontmatter
    const markdownWithMeta = fs.readFileSync(path.join('posts',filename), 'utf-8')
    //console.log(markdownWithMeta)

    const {data:frontmatter} = matter(markdownWithMeta)

    return{
      slug,
      frontmatter,
    }
  })

  //console.log(posts)

  return {
    props: {
      posts: posts.sort(sortByDate)
    }
  }
}

